// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: searchInfo.proto

package com.shoestp.mains.rpc.shoestp.pojo;

public final class GRPC_SendDataProto {
  private GRPC_SendDataProto() {}

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistryLite registry) {}

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions((com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public interface SearchInfoOrBuilder
      extends
      // @@protoc_insertion_point(interface_extends:SearchInfo)
      com.google.protobuf.MessageOrBuilder {

    /** <code>string keyword = 1;</code> */
    java.lang.String getKeyword();
    /** <code>string keyword = 1;</code> */
    com.google.protobuf.ByteString getKeywordBytes();

    /** <code>string ip = 2;</code> */
    java.lang.String getIp();
    /** <code>string ip = 2;</code> */
    com.google.protobuf.ByteString getIpBytes();

    /** <code>uint32 userId = 3;</code> */
    int getUserId();
  }
  /** Protobuf type {@code SearchInfo} */
  public static final class SearchInfo extends com.google.protobuf.GeneratedMessageV3
      implements
      // @@protoc_insertion_point(message_implements:SearchInfo)
      SearchInfoOrBuilder {
    private static final long serialVersionUID = 0L;
    // Use SearchInfo.newBuilder() to construct.
    private SearchInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }

    private SearchInfo() {
      keyword_ = "";
      ip_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
      return this.unknownFields;
    }

    private SearchInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10:
              {
                java.lang.String s = input.readStringRequireUtf8();

                keyword_ = s;
                break;
              }
            case 18:
              {
                java.lang.String s = input.readStringRequireUtf8();

                ip_ = s;
                break;
              }
            case 24:
              {
                userId_ = input.readUInt32();
                break;
              }
            default:
              {
                if (!parseUnknownField(input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }

    public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
      return com.shoestp.mains.rpc.shoestp.pojo.GRPC_SendDataProto
          .internal_static_SearchInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.shoestp.mains.rpc.shoestp.pojo.GRPC_SendDataProto
          .internal_static_SearchInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.shoestp.mains.rpc.shoestp.pojo.GRPC_SendDataProto.SearchInfo.class,
              com.shoestp.mains.rpc.shoestp.pojo.GRPC_SendDataProto.SearchInfo.Builder.class);
    }

    public static final int KEYWORD_FIELD_NUMBER = 1;
    private volatile java.lang.Object keyword_;
    /** <code>string keyword = 1;</code> */
    public java.lang.String getKeyword() {
      java.lang.Object ref = keyword_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        keyword_ = s;
        return s;
      }
    }
    /** <code>string keyword = 1;</code> */
    public com.google.protobuf.ByteString getKeywordBytes() {
      java.lang.Object ref = keyword_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
        keyword_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int IP_FIELD_NUMBER = 2;
    private volatile java.lang.Object ip_;
    /** <code>string ip = 2;</code> */
    public java.lang.String getIp() {
      java.lang.Object ref = ip_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ip_ = s;
        return s;
      }
    }
    /** <code>string ip = 2;</code> */
    public com.google.protobuf.ByteString getIpBytes() {
      java.lang.Object ref = ip_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
        ip_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USERID_FIELD_NUMBER = 3;
    private int userId_;
    /** <code>uint32 userId = 3;</code> */
    public int getUserId() {
      return userId_;
    }

    private byte memoizedIsInitialized = -1;

    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
      if (!getKeywordBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, keyword_);
      }
      if (!getIpBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, ip_);
      }
      if (userId_ != 0) {
        output.writeUInt32(3, userId_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getKeywordBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, keyword_);
      }
      if (!getIpBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, ip_);
      }
      if (userId_ != 0) {
        size += com.google.protobuf.CodedOutputStream.computeUInt32Size(3, userId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
        return true;
      }
      if (!(obj instanceof com.shoestp.mains.rpc.shoestp.pojo.GRPC_SendDataProto.SearchInfo)) {
        return super.equals(obj);
      }
      com.shoestp.mains.rpc.shoestp.pojo.GRPC_SendDataProto.SearchInfo other =
          (com.shoestp.mains.rpc.shoestp.pojo.GRPC_SendDataProto.SearchInfo) obj;

      if (!getKeyword().equals(other.getKeyword())) return false;
      if (!getIp().equals(other.getIp())) return false;
      if (getUserId() != other.getUserId()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + KEYWORD_FIELD_NUMBER;
      hash = (53 * hash) + getKeyword().hashCode();
      hash = (37 * hash) + IP_FIELD_NUMBER;
      hash = (53 * hash) + getIp().hashCode();
      hash = (37 * hash) + USERID_FIELD_NUMBER;
      hash = (53 * hash) + getUserId();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.shoestp.mains.rpc.shoestp.pojo.GRPC_SendDataProto.SearchInfo parseFrom(
        java.nio.ByteBuffer data) throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static com.shoestp.mains.rpc.shoestp.pojo.GRPC_SendDataProto.SearchInfo parseFrom(
        java.nio.ByteBuffer data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.shoestp.mains.rpc.shoestp.pojo.GRPC_SendDataProto.SearchInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static com.shoestp.mains.rpc.shoestp.pojo.GRPC_SendDataProto.SearchInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.shoestp.mains.rpc.shoestp.pojo.GRPC_SendDataProto.SearchInfo parseFrom(
        byte[] data) throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static com.shoestp.mains.rpc.shoestp.pojo.GRPC_SendDataProto.SearchInfo parseFrom(
        byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.shoestp.mains.rpc.shoestp.pojo.GRPC_SendDataProto.SearchInfo parseFrom(
        java.io.InputStream input) throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
    }

    public static com.shoestp.mains.rpc.shoestp.pojo.GRPC_SendDataProto.SearchInfo parseFrom(
        java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseWithIOException(
          PARSER, input, extensionRegistry);
    }

    public static com.shoestp.mains.rpc.shoestp.pojo.GRPC_SendDataProto.SearchInfo
        parseDelimitedFrom(java.io.InputStream input) throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
    }

    public static com.shoestp.mains.rpc.shoestp.pojo.GRPC_SendDataProto.SearchInfo
        parseDelimitedFrom(
            java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(
          PARSER, input, extensionRegistry);
    }

    public static com.shoestp.mains.rpc.shoestp.pojo.GRPC_SendDataProto.SearchInfo parseFrom(
        com.google.protobuf.CodedInputStream input) throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
    }

    public static com.shoestp.mains.rpc.shoestp.pojo.GRPC_SendDataProto.SearchInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseWithIOException(
          PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() {
      return newBuilder();
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(
        com.shoestp.mains.rpc.shoestp.pojo.GRPC_SendDataProto.SearchInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /** Protobuf type {@code SearchInfo} */
    public static final class Builder
        extends com.google.protobuf.GeneratedMessageV3.Builder<Builder>
        implements
        // @@protoc_insertion_point(builder_implements:SearchInfo)
        com.shoestp.mains.rpc.shoestp.pojo.GRPC_SendDataProto.SearchInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
        return com.shoestp.mains.rpc.shoestp.pojo.GRPC_SendDataProto
            .internal_static_SearchInfo_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.shoestp.mains.rpc.shoestp.pojo.GRPC_SendDataProto
            .internal_static_SearchInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.shoestp.mains.rpc.shoestp.pojo.GRPC_SendDataProto.SearchInfo.class,
                com.shoestp.mains.rpc.shoestp.pojo.GRPC_SendDataProto.SearchInfo.Builder.class);
      }

      // Construct using
      // com.shoestp.mains.rpc.shoestp.pojo.GRPC_SendDataProto.SearchInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {}
      }

      @java.lang.Override
      public Builder clear() {
        super.clear();
        keyword_ = "";

        ip_ = "";

        userId_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
        return com.shoestp.mains.rpc.shoestp.pojo.GRPC_SendDataProto
            .internal_static_SearchInfo_descriptor;
      }

      @java.lang.Override
      public com.shoestp.mains.rpc.shoestp.pojo.GRPC_SendDataProto.SearchInfo
          getDefaultInstanceForType() {
        return com.shoestp.mains.rpc.shoestp.pojo.GRPC_SendDataProto.SearchInfo
            .getDefaultInstance();
      }

      @java.lang.Override
      public com.shoestp.mains.rpc.shoestp.pojo.GRPC_SendDataProto.SearchInfo build() {
        com.shoestp.mains.rpc.shoestp.pojo.GRPC_SendDataProto.SearchInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.shoestp.mains.rpc.shoestp.pojo.GRPC_SendDataProto.SearchInfo buildPartial() {
        com.shoestp.mains.rpc.shoestp.pojo.GRPC_SendDataProto.SearchInfo result =
            new com.shoestp.mains.rpc.shoestp.pojo.GRPC_SendDataProto.SearchInfo(this);
        result.keyword_ = keyword_;
        result.ip_ = ip_;
        result.userId_ = userId_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }

      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
        return super.setField(field, value);
      }

      @java.lang.Override
      public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }

      @java.lang.Override
      public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }

      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index,
          java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }

      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.shoestp.mains.rpc.shoestp.pojo.GRPC_SendDataProto.SearchInfo) {
          return mergeFrom(
              (com.shoestp.mains.rpc.shoestp.pojo.GRPC_SendDataProto.SearchInfo) other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(
          com.shoestp.mains.rpc.shoestp.pojo.GRPC_SendDataProto.SearchInfo other) {
        if (other
            == com.shoestp.mains.rpc.shoestp.pojo.GRPC_SendDataProto.SearchInfo
                .getDefaultInstance()) return this;
        if (!other.getKeyword().isEmpty()) {
          keyword_ = other.keyword_;
          onChanged();
        }
        if (!other.getIp().isEmpty()) {
          ip_ = other.ip_;
          onChanged();
        }
        if (other.getUserId() != 0) {
          setUserId(other.getUserId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.shoestp.mains.rpc.shoestp.pojo.GRPC_SendDataProto.SearchInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage =
              (com.shoestp.mains.rpc.shoestp.pojo.GRPC_SendDataProto.SearchInfo)
                  e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object keyword_ = "";
      /** <code>string keyword = 1;</code> */
      public java.lang.String getKeyword() {
        java.lang.Object ref = keyword_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          keyword_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /** <code>string keyword = 1;</code> */
      public com.google.protobuf.ByteString getKeywordBytes() {
        java.lang.Object ref = keyword_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
          keyword_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /** <code>string keyword = 1;</code> */
      public Builder setKeyword(java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }

        keyword_ = value;
        onChanged();
        return this;
      }
      /** <code>string keyword = 1;</code> */
      public Builder clearKeyword() {

        keyword_ = getDefaultInstance().getKeyword();
        onChanged();
        return this;
      }
      /** <code>string keyword = 1;</code> */
      public Builder setKeywordBytes(com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);

        keyword_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object ip_ = "";
      /** <code>string ip = 2;</code> */
      public java.lang.String getIp() {
        java.lang.Object ref = ip_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          ip_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /** <code>string ip = 2;</code> */
      public com.google.protobuf.ByteString getIpBytes() {
        java.lang.Object ref = ip_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
          ip_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /** <code>string ip = 2;</code> */
      public Builder setIp(java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }

        ip_ = value;
        onChanged();
        return this;
      }
      /** <code>string ip = 2;</code> */
      public Builder clearIp() {

        ip_ = getDefaultInstance().getIp();
        onChanged();
        return this;
      }
      /** <code>string ip = 2;</code> */
      public Builder setIpBytes(com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);

        ip_ = value;
        onChanged();
        return this;
      }

      private int userId_;
      /** <code>uint32 userId = 3;</code> */
      public int getUserId() {
        return userId_;
      }
      /** <code>uint32 userId = 3;</code> */
      public Builder setUserId(int value) {

        userId_ = value;
        onChanged();
        return this;
      }
      /** <code>uint32 userId = 3;</code> */
      public Builder clearUserId() {

        userId_ = 0;
        onChanged();
        return this;
      }

      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }

      // @@protoc_insertion_point(builder_scope:SearchInfo)
    }

    // @@protoc_insertion_point(class_scope:SearchInfo)
    private static final com.shoestp.mains.rpc.shoestp.pojo.GRPC_SendDataProto.SearchInfo
        DEFAULT_INSTANCE;

    static {
      DEFAULT_INSTANCE = new com.shoestp.mains.rpc.shoestp.pojo.GRPC_SendDataProto.SearchInfo();
    }

    public static com.shoestp.mains.rpc.shoestp.pojo.GRPC_SendDataProto.SearchInfo
        getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SearchInfo> PARSER =
        new com.google.protobuf.AbstractParser<SearchInfo>() {
          @java.lang.Override
          public SearchInfo parsePartialFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws com.google.protobuf.InvalidProtocolBufferException {
            return new SearchInfo(input, extensionRegistry);
          }
        };

    public static com.google.protobuf.Parser<SearchInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SearchInfo> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.shoestp.mains.rpc.shoestp.pojo.GRPC_SendDataProto.SearchInfo
        getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }
  }

  public interface ViewInfoOrBuilder
      extends
      // @@protoc_insertion_point(interface_extends:ViewInfo)
      com.google.protobuf.MessageOrBuilder {

    /** <code>string url = 1;</code> */
    java.lang.String getUrl();
    /** <code>string url = 1;</code> */
    com.google.protobuf.ByteString getUrlBytes();

    /** <code>string useragent = 2;</code> */
    java.lang.String getUseragent();
    /** <code>string useragent = 2;</code> */
    com.google.protobuf.ByteString getUseragentBytes();

    /** <code>string ip = 3;</code> */
    java.lang.String getIp();
    /** <code>string ip = 3;</code> */
    com.google.protobuf.ByteString getIpBytes();

    /** <code>uint32 userId = 4;</code> */
    int getUserId();

    /** <code>string referer = 5;</code> */
    java.lang.String getReferer();
    /** <code>string referer = 5;</code> */
    com.google.protobuf.ByteString getRefererBytes();
  }
  /** Protobuf type {@code ViewInfo} */
  public static final class ViewInfo extends com.google.protobuf.GeneratedMessageV3
      implements
      // @@protoc_insertion_point(message_implements:ViewInfo)
      ViewInfoOrBuilder {
    private static final long serialVersionUID = 0L;
    // Use ViewInfo.newBuilder() to construct.
    private ViewInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }

    private ViewInfo() {
      url_ = "";
      useragent_ = "";
      ip_ = "";
      referer_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
      return this.unknownFields;
    }

    private ViewInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10:
              {
                java.lang.String s = input.readStringRequireUtf8();

                url_ = s;
                break;
              }
            case 18:
              {
                java.lang.String s = input.readStringRequireUtf8();

                useragent_ = s;
                break;
              }
            case 26:
              {
                java.lang.String s = input.readStringRequireUtf8();

                ip_ = s;
                break;
              }
            case 32:
              {
                userId_ = input.readUInt32();
                break;
              }
            case 42:
              {
                java.lang.String s = input.readStringRequireUtf8();

                referer_ = s;
                break;
              }
            default:
              {
                if (!parseUnknownField(input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }

    public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
      return com.shoestp.mains.rpc.shoestp.pojo.GRPC_SendDataProto
          .internal_static_ViewInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.shoestp.mains.rpc.shoestp.pojo.GRPC_SendDataProto
          .internal_static_ViewInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.shoestp.mains.rpc.shoestp.pojo.GRPC_SendDataProto.ViewInfo.class,
              com.shoestp.mains.rpc.shoestp.pojo.GRPC_SendDataProto.ViewInfo.Builder.class);
    }

    public static final int URL_FIELD_NUMBER = 1;
    private volatile java.lang.Object url_;
    /** <code>string url = 1;</code> */
    public java.lang.String getUrl() {
      java.lang.Object ref = url_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        url_ = s;
        return s;
      }
    }
    /** <code>string url = 1;</code> */
    public com.google.protobuf.ByteString getUrlBytes() {
      java.lang.Object ref = url_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
        url_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USERAGENT_FIELD_NUMBER = 2;
    private volatile java.lang.Object useragent_;
    /** <code>string useragent = 2;</code> */
    public java.lang.String getUseragent() {
      java.lang.Object ref = useragent_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        useragent_ = s;
        return s;
      }
    }
    /** <code>string useragent = 2;</code> */
    public com.google.protobuf.ByteString getUseragentBytes() {
      java.lang.Object ref = useragent_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
        useragent_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int IP_FIELD_NUMBER = 3;
    private volatile java.lang.Object ip_;
    /** <code>string ip = 3;</code> */
    public java.lang.String getIp() {
      java.lang.Object ref = ip_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ip_ = s;
        return s;
      }
    }
    /** <code>string ip = 3;</code> */
    public com.google.protobuf.ByteString getIpBytes() {
      java.lang.Object ref = ip_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
        ip_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USERID_FIELD_NUMBER = 4;
    private int userId_;
    /** <code>uint32 userId = 4;</code> */
    public int getUserId() {
      return userId_;
    }

    public static final int REFERER_FIELD_NUMBER = 5;
    private volatile java.lang.Object referer_;
    /** <code>string referer = 5;</code> */
    public java.lang.String getReferer() {
      java.lang.Object ref = referer_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        referer_ = s;
        return s;
      }
    }
    /** <code>string referer = 5;</code> */
    public com.google.protobuf.ByteString getRefererBytes() {
      java.lang.Object ref = referer_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
        referer_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;

    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
      if (!getUrlBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, url_);
      }
      if (!getUseragentBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, useragent_);
      }
      if (!getIpBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, ip_);
      }
      if (userId_ != 0) {
        output.writeUInt32(4, userId_);
      }
      if (!getRefererBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, referer_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getUrlBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, url_);
      }
      if (!getUseragentBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, useragent_);
      }
      if (!getIpBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, ip_);
      }
      if (userId_ != 0) {
        size += com.google.protobuf.CodedOutputStream.computeUInt32Size(4, userId_);
      }
      if (!getRefererBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, referer_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
        return true;
      }
      if (!(obj instanceof com.shoestp.mains.rpc.shoestp.pojo.GRPC_SendDataProto.ViewInfo)) {
        return super.equals(obj);
      }
      com.shoestp.mains.rpc.shoestp.pojo.GRPC_SendDataProto.ViewInfo other =
          (com.shoestp.mains.rpc.shoestp.pojo.GRPC_SendDataProto.ViewInfo) obj;

      if (!getUrl().equals(other.getUrl())) return false;
      if (!getUseragent().equals(other.getUseragent())) return false;
      if (!getIp().equals(other.getIp())) return false;
      if (getUserId() != other.getUserId()) return false;
      if (!getReferer().equals(other.getReferer())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + URL_FIELD_NUMBER;
      hash = (53 * hash) + getUrl().hashCode();
      hash = (37 * hash) + USERAGENT_FIELD_NUMBER;
      hash = (53 * hash) + getUseragent().hashCode();
      hash = (37 * hash) + IP_FIELD_NUMBER;
      hash = (53 * hash) + getIp().hashCode();
      hash = (37 * hash) + USERID_FIELD_NUMBER;
      hash = (53 * hash) + getUserId();
      hash = (37 * hash) + REFERER_FIELD_NUMBER;
      hash = (53 * hash) + getReferer().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.shoestp.mains.rpc.shoestp.pojo.GRPC_SendDataProto.ViewInfo parseFrom(
        java.nio.ByteBuffer data) throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static com.shoestp.mains.rpc.shoestp.pojo.GRPC_SendDataProto.ViewInfo parseFrom(
        java.nio.ByteBuffer data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.shoestp.mains.rpc.shoestp.pojo.GRPC_SendDataProto.ViewInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static com.shoestp.mains.rpc.shoestp.pojo.GRPC_SendDataProto.ViewInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.shoestp.mains.rpc.shoestp.pojo.GRPC_SendDataProto.ViewInfo parseFrom(
        byte[] data) throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static com.shoestp.mains.rpc.shoestp.pojo.GRPC_SendDataProto.ViewInfo parseFrom(
        byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.shoestp.mains.rpc.shoestp.pojo.GRPC_SendDataProto.ViewInfo parseFrom(
        java.io.InputStream input) throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
    }

    public static com.shoestp.mains.rpc.shoestp.pojo.GRPC_SendDataProto.ViewInfo parseFrom(
        java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseWithIOException(
          PARSER, input, extensionRegistry);
    }

    public static com.shoestp.mains.rpc.shoestp.pojo.GRPC_SendDataProto.ViewInfo parseDelimitedFrom(
        java.io.InputStream input) throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
    }

    public static com.shoestp.mains.rpc.shoestp.pojo.GRPC_SendDataProto.ViewInfo parseDelimitedFrom(
        java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(
          PARSER, input, extensionRegistry);
    }

    public static com.shoestp.mains.rpc.shoestp.pojo.GRPC_SendDataProto.ViewInfo parseFrom(
        com.google.protobuf.CodedInputStream input) throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
    }

    public static com.shoestp.mains.rpc.shoestp.pojo.GRPC_SendDataProto.ViewInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseWithIOException(
          PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() {
      return newBuilder();
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(
        com.shoestp.mains.rpc.shoestp.pojo.GRPC_SendDataProto.ViewInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /** Protobuf type {@code ViewInfo} */
    public static final class Builder
        extends com.google.protobuf.GeneratedMessageV3.Builder<Builder>
        implements
        // @@protoc_insertion_point(builder_implements:ViewInfo)
        com.shoestp.mains.rpc.shoestp.pojo.GRPC_SendDataProto.ViewInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
        return com.shoestp.mains.rpc.shoestp.pojo.GRPC_SendDataProto
            .internal_static_ViewInfo_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.shoestp.mains.rpc.shoestp.pojo.GRPC_SendDataProto
            .internal_static_ViewInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.shoestp.mains.rpc.shoestp.pojo.GRPC_SendDataProto.ViewInfo.class,
                com.shoestp.mains.rpc.shoestp.pojo.GRPC_SendDataProto.ViewInfo.Builder.class);
      }

      // Construct using com.shoestp.mains.rpc.shoestp.pojo.GRPC_SendDataProto.ViewInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {}
      }

      @java.lang.Override
      public Builder clear() {
        super.clear();
        url_ = "";

        useragent_ = "";

        ip_ = "";

        userId_ = 0;

        referer_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
        return com.shoestp.mains.rpc.shoestp.pojo.GRPC_SendDataProto
            .internal_static_ViewInfo_descriptor;
      }

      @java.lang.Override
      public com.shoestp.mains.rpc.shoestp.pojo.GRPC_SendDataProto.ViewInfo
          getDefaultInstanceForType() {
        return com.shoestp.mains.rpc.shoestp.pojo.GRPC_SendDataProto.ViewInfo.getDefaultInstance();
      }

      @java.lang.Override
      public com.shoestp.mains.rpc.shoestp.pojo.GRPC_SendDataProto.ViewInfo build() {
        com.shoestp.mains.rpc.shoestp.pojo.GRPC_SendDataProto.ViewInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.shoestp.mains.rpc.shoestp.pojo.GRPC_SendDataProto.ViewInfo buildPartial() {
        com.shoestp.mains.rpc.shoestp.pojo.GRPC_SendDataProto.ViewInfo result =
            new com.shoestp.mains.rpc.shoestp.pojo.GRPC_SendDataProto.ViewInfo(this);
        result.url_ = url_;
        result.useragent_ = useragent_;
        result.ip_ = ip_;
        result.userId_ = userId_;
        result.referer_ = referer_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }

      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
        return super.setField(field, value);
      }

      @java.lang.Override
      public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }

      @java.lang.Override
      public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }

      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index,
          java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }

      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.shoestp.mains.rpc.shoestp.pojo.GRPC_SendDataProto.ViewInfo) {
          return mergeFrom((com.shoestp.mains.rpc.shoestp.pojo.GRPC_SendDataProto.ViewInfo) other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(
          com.shoestp.mains.rpc.shoestp.pojo.GRPC_SendDataProto.ViewInfo other) {
        if (other
            == com.shoestp.mains.rpc.shoestp.pojo.GRPC_SendDataProto.ViewInfo.getDefaultInstance())
          return this;
        if (!other.getUrl().isEmpty()) {
          url_ = other.url_;
          onChanged();
        }
        if (!other.getUseragent().isEmpty()) {
          useragent_ = other.useragent_;
          onChanged();
        }
        if (!other.getIp().isEmpty()) {
          ip_ = other.ip_;
          onChanged();
        }
        if (other.getUserId() != 0) {
          setUserId(other.getUserId());
        }
        if (!other.getReferer().isEmpty()) {
          referer_ = other.referer_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.shoestp.mains.rpc.shoestp.pojo.GRPC_SendDataProto.ViewInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage =
              (com.shoestp.mains.rpc.shoestp.pojo.GRPC_SendDataProto.ViewInfo)
                  e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object url_ = "";
      /** <code>string url = 1;</code> */
      public java.lang.String getUrl() {
        java.lang.Object ref = url_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          url_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /** <code>string url = 1;</code> */
      public com.google.protobuf.ByteString getUrlBytes() {
        java.lang.Object ref = url_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
          url_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /** <code>string url = 1;</code> */
      public Builder setUrl(java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }

        url_ = value;
        onChanged();
        return this;
      }
      /** <code>string url = 1;</code> */
      public Builder clearUrl() {

        url_ = getDefaultInstance().getUrl();
        onChanged();
        return this;
      }
      /** <code>string url = 1;</code> */
      public Builder setUrlBytes(com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);

        url_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object useragent_ = "";
      /** <code>string useragent = 2;</code> */
      public java.lang.String getUseragent() {
        java.lang.Object ref = useragent_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          useragent_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /** <code>string useragent = 2;</code> */
      public com.google.protobuf.ByteString getUseragentBytes() {
        java.lang.Object ref = useragent_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
          useragent_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /** <code>string useragent = 2;</code> */
      public Builder setUseragent(java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }

        useragent_ = value;
        onChanged();
        return this;
      }
      /** <code>string useragent = 2;</code> */
      public Builder clearUseragent() {

        useragent_ = getDefaultInstance().getUseragent();
        onChanged();
        return this;
      }
      /** <code>string useragent = 2;</code> */
      public Builder setUseragentBytes(com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);

        useragent_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object ip_ = "";
      /** <code>string ip = 3;</code> */
      public java.lang.String getIp() {
        java.lang.Object ref = ip_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          ip_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /** <code>string ip = 3;</code> */
      public com.google.protobuf.ByteString getIpBytes() {
        java.lang.Object ref = ip_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
          ip_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /** <code>string ip = 3;</code> */
      public Builder setIp(java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }

        ip_ = value;
        onChanged();
        return this;
      }
      /** <code>string ip = 3;</code> */
      public Builder clearIp() {

        ip_ = getDefaultInstance().getIp();
        onChanged();
        return this;
      }
      /** <code>string ip = 3;</code> */
      public Builder setIpBytes(com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);

        ip_ = value;
        onChanged();
        return this;
      }

      private int userId_;
      /** <code>uint32 userId = 4;</code> */
      public int getUserId() {
        return userId_;
      }
      /** <code>uint32 userId = 4;</code> */
      public Builder setUserId(int value) {

        userId_ = value;
        onChanged();
        return this;
      }
      /** <code>uint32 userId = 4;</code> */
      public Builder clearUserId() {

        userId_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object referer_ = "";
      /** <code>string referer = 5;</code> */
      public java.lang.String getReferer() {
        java.lang.Object ref = referer_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          referer_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /** <code>string referer = 5;</code> */
      public com.google.protobuf.ByteString getRefererBytes() {
        java.lang.Object ref = referer_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
          referer_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /** <code>string referer = 5;</code> */
      public Builder setReferer(java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }

        referer_ = value;
        onChanged();
        return this;
      }
      /** <code>string referer = 5;</code> */
      public Builder clearReferer() {

        referer_ = getDefaultInstance().getReferer();
        onChanged();
        return this;
      }
      /** <code>string referer = 5;</code> */
      public Builder setRefererBytes(com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);

        referer_ = value;
        onChanged();
        return this;
      }

      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }

      // @@protoc_insertion_point(builder_scope:ViewInfo)
    }

    // @@protoc_insertion_point(class_scope:ViewInfo)
    private static final com.shoestp.mains.rpc.shoestp.pojo.GRPC_SendDataProto.ViewInfo
        DEFAULT_INSTANCE;

    static {
      DEFAULT_INSTANCE = new com.shoestp.mains.rpc.shoestp.pojo.GRPC_SendDataProto.ViewInfo();
    }

    public static com.shoestp.mains.rpc.shoestp.pojo.GRPC_SendDataProto.ViewInfo
        getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ViewInfo> PARSER =
        new com.google.protobuf.AbstractParser<ViewInfo>() {
          @java.lang.Override
          public ViewInfo parsePartialFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws com.google.protobuf.InvalidProtocolBufferException {
            return new ViewInfo(input, extensionRegistry);
          }
        };

    public static com.google.protobuf.Parser<ViewInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ViewInfo> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.shoestp.mains.rpc.shoestp.pojo.GRPC_SendDataProto.ViewInfo
        getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }
  }

  public interface InquiryOrBuilder
      extends
      // @@protoc_insertion_point(interface_extends:Inquiry)
      com.google.protobuf.MessageOrBuilder {

    /** <code>uint32 type = 1;</code> */
    int getType();

    /** <code>uint32 inquiryId = 2;</code> */
    int getInquiryId();

    /** <code>string referer = 3;</code> */
    java.lang.String getReferer();
    /** <code>string referer = 3;</code> */
    com.google.protobuf.ByteString getRefererBytes();
  }
  /** Protobuf type {@code Inquiry} */
  public static final class Inquiry extends com.google.protobuf.GeneratedMessageV3
      implements
      // @@protoc_insertion_point(message_implements:Inquiry)
      InquiryOrBuilder {
    private static final long serialVersionUID = 0L;
    // Use Inquiry.newBuilder() to construct.
    private Inquiry(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }

    private Inquiry() {
      referer_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
      return this.unknownFields;
    }

    private Inquiry(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8:
              {
                type_ = input.readUInt32();
                break;
              }
            case 16:
              {
                inquiryId_ = input.readUInt32();
                break;
              }
            case 26:
              {
                java.lang.String s = input.readStringRequireUtf8();

                referer_ = s;
                break;
              }
            default:
              {
                if (!parseUnknownField(input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }

    public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
      return com.shoestp.mains.rpc.shoestp.pojo.GRPC_SendDataProto
          .internal_static_Inquiry_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.shoestp.mains.rpc.shoestp.pojo.GRPC_SendDataProto
          .internal_static_Inquiry_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.shoestp.mains.rpc.shoestp.pojo.GRPC_SendDataProto.Inquiry.class,
              com.shoestp.mains.rpc.shoestp.pojo.GRPC_SendDataProto.Inquiry.Builder.class);
    }

    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /** <code>uint32 type = 1;</code> */
    public int getType() {
      return type_;
    }

    public static final int INQUIRYID_FIELD_NUMBER = 2;
    private int inquiryId_;
    /** <code>uint32 inquiryId = 2;</code> */
    public int getInquiryId() {
      return inquiryId_;
    }

    public static final int REFERER_FIELD_NUMBER = 3;
    private volatile java.lang.Object referer_;
    /** <code>string referer = 3;</code> */
    public java.lang.String getReferer() {
      java.lang.Object ref = referer_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        referer_ = s;
        return s;
      }
    }
    /** <code>string referer = 3;</code> */
    public com.google.protobuf.ByteString getRefererBytes() {
      java.lang.Object ref = referer_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
        referer_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;

    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
      if (type_ != 0) {
        output.writeUInt32(1, type_);
      }
      if (inquiryId_ != 0) {
        output.writeUInt32(2, inquiryId_);
      }
      if (!getRefererBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, referer_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (type_ != 0) {
        size += com.google.protobuf.CodedOutputStream.computeUInt32Size(1, type_);
      }
      if (inquiryId_ != 0) {
        size += com.google.protobuf.CodedOutputStream.computeUInt32Size(2, inquiryId_);
      }
      if (!getRefererBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, referer_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
        return true;
      }
      if (!(obj instanceof com.shoestp.mains.rpc.shoestp.pojo.GRPC_SendDataProto.Inquiry)) {
        return super.equals(obj);
      }
      com.shoestp.mains.rpc.shoestp.pojo.GRPC_SendDataProto.Inquiry other =
          (com.shoestp.mains.rpc.shoestp.pojo.GRPC_SendDataProto.Inquiry) obj;

      if (getType() != other.getType()) return false;
      if (getInquiryId() != other.getInquiryId()) return false;
      if (!getReferer().equals(other.getReferer())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getType();
      hash = (37 * hash) + INQUIRYID_FIELD_NUMBER;
      hash = (53 * hash) + getInquiryId();
      hash = (37 * hash) + REFERER_FIELD_NUMBER;
      hash = (53 * hash) + getReferer().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.shoestp.mains.rpc.shoestp.pojo.GRPC_SendDataProto.Inquiry parseFrom(
        java.nio.ByteBuffer data) throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static com.shoestp.mains.rpc.shoestp.pojo.GRPC_SendDataProto.Inquiry parseFrom(
        java.nio.ByteBuffer data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.shoestp.mains.rpc.shoestp.pojo.GRPC_SendDataProto.Inquiry parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static com.shoestp.mains.rpc.shoestp.pojo.GRPC_SendDataProto.Inquiry parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.shoestp.mains.rpc.shoestp.pojo.GRPC_SendDataProto.Inquiry parseFrom(
        byte[] data) throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static com.shoestp.mains.rpc.shoestp.pojo.GRPC_SendDataProto.Inquiry parseFrom(
        byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.shoestp.mains.rpc.shoestp.pojo.GRPC_SendDataProto.Inquiry parseFrom(
        java.io.InputStream input) throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
    }

    public static com.shoestp.mains.rpc.shoestp.pojo.GRPC_SendDataProto.Inquiry parseFrom(
        java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseWithIOException(
          PARSER, input, extensionRegistry);
    }

    public static com.shoestp.mains.rpc.shoestp.pojo.GRPC_SendDataProto.Inquiry parseDelimitedFrom(
        java.io.InputStream input) throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
    }

    public static com.shoestp.mains.rpc.shoestp.pojo.GRPC_SendDataProto.Inquiry parseDelimitedFrom(
        java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(
          PARSER, input, extensionRegistry);
    }

    public static com.shoestp.mains.rpc.shoestp.pojo.GRPC_SendDataProto.Inquiry parseFrom(
        com.google.protobuf.CodedInputStream input) throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
    }

    public static com.shoestp.mains.rpc.shoestp.pojo.GRPC_SendDataProto.Inquiry parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseWithIOException(
          PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() {
      return newBuilder();
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(
        com.shoestp.mains.rpc.shoestp.pojo.GRPC_SendDataProto.Inquiry prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /** Protobuf type {@code Inquiry} */
    public static final class Builder
        extends com.google.protobuf.GeneratedMessageV3.Builder<Builder>
        implements
        // @@protoc_insertion_point(builder_implements:Inquiry)
        com.shoestp.mains.rpc.shoestp.pojo.GRPC_SendDataProto.InquiryOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
        return com.shoestp.mains.rpc.shoestp.pojo.GRPC_SendDataProto
            .internal_static_Inquiry_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.shoestp.mains.rpc.shoestp.pojo.GRPC_SendDataProto
            .internal_static_Inquiry_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.shoestp.mains.rpc.shoestp.pojo.GRPC_SendDataProto.Inquiry.class,
                com.shoestp.mains.rpc.shoestp.pojo.GRPC_SendDataProto.Inquiry.Builder.class);
      }

      // Construct using com.shoestp.mains.rpc.shoestp.pojo.GRPC_SendDataProto.Inquiry.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {}
      }

      @java.lang.Override
      public Builder clear() {
        super.clear();
        type_ = 0;

        inquiryId_ = 0;

        referer_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
        return com.shoestp.mains.rpc.shoestp.pojo.GRPC_SendDataProto
            .internal_static_Inquiry_descriptor;
      }

      @java.lang.Override
      public com.shoestp.mains.rpc.shoestp.pojo.GRPC_SendDataProto.Inquiry
          getDefaultInstanceForType() {
        return com.shoestp.mains.rpc.shoestp.pojo.GRPC_SendDataProto.Inquiry.getDefaultInstance();
      }

      @java.lang.Override
      public com.shoestp.mains.rpc.shoestp.pojo.GRPC_SendDataProto.Inquiry build() {
        com.shoestp.mains.rpc.shoestp.pojo.GRPC_SendDataProto.Inquiry result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.shoestp.mains.rpc.shoestp.pojo.GRPC_SendDataProto.Inquiry buildPartial() {
        com.shoestp.mains.rpc.shoestp.pojo.GRPC_SendDataProto.Inquiry result =
            new com.shoestp.mains.rpc.shoestp.pojo.GRPC_SendDataProto.Inquiry(this);
        result.type_ = type_;
        result.inquiryId_ = inquiryId_;
        result.referer_ = referer_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }

      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
        return super.setField(field, value);
      }

      @java.lang.Override
      public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }

      @java.lang.Override
      public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }

      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index,
          java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }

      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.shoestp.mains.rpc.shoestp.pojo.GRPC_SendDataProto.Inquiry) {
          return mergeFrom((com.shoestp.mains.rpc.shoestp.pojo.GRPC_SendDataProto.Inquiry) other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(
          com.shoestp.mains.rpc.shoestp.pojo.GRPC_SendDataProto.Inquiry other) {
        if (other
            == com.shoestp.mains.rpc.shoestp.pojo.GRPC_SendDataProto.Inquiry.getDefaultInstance())
          return this;
        if (other.getType() != 0) {
          setType(other.getType());
        }
        if (other.getInquiryId() != 0) {
          setInquiryId(other.getInquiryId());
        }
        if (!other.getReferer().isEmpty()) {
          referer_ = other.referer_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.shoestp.mains.rpc.shoestp.pojo.GRPC_SendDataProto.Inquiry parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage =
              (com.shoestp.mains.rpc.shoestp.pojo.GRPC_SendDataProto.Inquiry)
                  e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int type_;
      /** <code>uint32 type = 1;</code> */
      public int getType() {
        return type_;
      }
      /** <code>uint32 type = 1;</code> */
      public Builder setType(int value) {

        type_ = value;
        onChanged();
        return this;
      }
      /** <code>uint32 type = 1;</code> */
      public Builder clearType() {

        type_ = 0;
        onChanged();
        return this;
      }

      private int inquiryId_;
      /** <code>uint32 inquiryId = 2;</code> */
      public int getInquiryId() {
        return inquiryId_;
      }
      /** <code>uint32 inquiryId = 2;</code> */
      public Builder setInquiryId(int value) {

        inquiryId_ = value;
        onChanged();
        return this;
      }
      /** <code>uint32 inquiryId = 2;</code> */
      public Builder clearInquiryId() {

        inquiryId_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object referer_ = "";
      /** <code>string referer = 3;</code> */
      public java.lang.String getReferer() {
        java.lang.Object ref = referer_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          referer_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /** <code>string referer = 3;</code> */
      public com.google.protobuf.ByteString getRefererBytes() {
        java.lang.Object ref = referer_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
          referer_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /** <code>string referer = 3;</code> */
      public Builder setReferer(java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }

        referer_ = value;
        onChanged();
        return this;
      }
      /** <code>string referer = 3;</code> */
      public Builder clearReferer() {

        referer_ = getDefaultInstance().getReferer();
        onChanged();
        return this;
      }
      /** <code>string referer = 3;</code> */
      public Builder setRefererBytes(com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);

        referer_ = value;
        onChanged();
        return this;
      }

      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }

      // @@protoc_insertion_point(builder_scope:Inquiry)
    }

    // @@protoc_insertion_point(class_scope:Inquiry)
    private static final com.shoestp.mains.rpc.shoestp.pojo.GRPC_SendDataProto.Inquiry
        DEFAULT_INSTANCE;

    static {
      DEFAULT_INSTANCE = new com.shoestp.mains.rpc.shoestp.pojo.GRPC_SendDataProto.Inquiry();
    }

    public static com.shoestp.mains.rpc.shoestp.pojo.GRPC_SendDataProto.Inquiry
        getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Inquiry> PARSER =
        new com.google.protobuf.AbstractParser<Inquiry>() {
          @java.lang.Override
          public Inquiry parsePartialFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws com.google.protobuf.InvalidProtocolBufferException {
            return new Inquiry(input, extensionRegistry);
          }
        };

    public static com.google.protobuf.Parser<Inquiry> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Inquiry> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.shoestp.mains.rpc.shoestp.pojo.GRPC_SendDataProto.Inquiry
        getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }
  }

  private static final com.google.protobuf.Descriptors.Descriptor
      internal_static_SearchInfo_descriptor;
  private static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SearchInfo_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
      internal_static_ViewInfo_descriptor;
  private static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ViewInfo_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
      internal_static_Inquiry_descriptor;
  private static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Inquiry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
    return descriptor;
  }

  private static com.google.protobuf.Descriptors.FileDescriptor descriptor;

  static {
    java.lang.String[] descriptorData = {
      "\n\020searchInfo.proto\032\014result.proto\"9\n\nSear"
          + "chInfo\022\017\n\007keyword\030\001 \001(\t\022\n\n\002ip\030\002 \001(\t\022\016\n\006u"
          + "serId\030\003 \001(\r\"W\n\010ViewInfo\022\013\n\003url\030\001 \001(\t\022\021\n\t"
          + "useragent\030\002 \001(\t\022\n\n\002ip\030\003 \001(\t\022\016\n\006userId\030\004 "
          + "\001(\r\022\017\n\007referer\030\005 \001(\t\";\n\007Inquiry\022\014\n\004type\030"
          + "\001 \001(\r\022\021\n\tinquiryId\030\002 \001(\r\022\017\n\007referer\030\003 \001("
          + "\t2\204\001\n\014SendDataUtil\022&\n\nsendSearch\022\013.Searc"
          + "hInfo\032\007.Result(\0010\001\022&\n\014sendViewInfo\022\t.Vie"
          + "wInfo\032\007.Result(\0010\001\022$\n\013sendInquiry\022\010.Inqu"
          + "iry\032\007.Result(\0010\001BG\n\"com.shoestp.mains.rp"
          + "c.shoestp.pojoB\022GRPC_SendDataProtoP\000\242\002\nS"
          + "earchInfob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(
        descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.shoestp.mains.rpc.shoestp.pojo.GRPC_ResultProto.getDescriptor(),
        },
        assigner);
    internal_static_SearchInfo_descriptor = getDescriptor().getMessageTypes().get(0);
    internal_static_SearchInfo_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_SearchInfo_descriptor,
            new java.lang.String[] {
              "Keyword", "Ip", "UserId",
            });
    internal_static_ViewInfo_descriptor = getDescriptor().getMessageTypes().get(1);
    internal_static_ViewInfo_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_ViewInfo_descriptor,
            new java.lang.String[] {
              "Url", "Useragent", "Ip", "UserId", "Referer",
            });
    internal_static_Inquiry_descriptor = getDescriptor().getMessageTypes().get(2);
    internal_static_Inquiry_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_Inquiry_descriptor,
            new java.lang.String[] {
              "Type", "InquiryId", "Referer",
            });
    com.shoestp.mains.rpc.shoestp.pojo.GRPC_ResultProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
