server:
  address: 0.0.0.0
  http2:
    enabled: true
  port: 80
spring:
  cache:
    jcache:
      config: ehcacheConfig.xml
  datasource:
#    url: jdbc:mysql://192.168.99.100:3306/test?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    url: jdbc:mysql://localhost:3306/dataview?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      idle-timeout: 30000
      auto-commit: true
      pool-name: bigdata
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  jpa:
    hibernate:
#      ddl-auto: create-drop
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
  messages: lang
  quartz:
    job-store-type: memory

