server:
  address: 0.0.0.0
  #  http2:
  #    enabled: true
  port: 80
spring:
  cache:
    jcache:
      config: classpath:ehcacheConfig.xml
  datasource:
    url: jdbc:mysql://192.168.99.100:3306/test?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    #    url: jdbc:mysql://localhost:3306/dataview?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      idle-timeout: 30000
      auto-commit: true
      pool-name: bigdata
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  jpa:
    hibernate:
      ddl-auto: create-drop
      #      ddl-auto: update
      use-new-id-generator-mappings: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
  messages: lang
  quartz:
    job-store-type: memory
rpc:
  host: 0.0.0.0
  port: 888

